# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d43fd86e46d30c92bb171fba42a604332f6d4088ed1b4ad8696ccb55438a98ba3b1b1967ce03dd5012e8097598f08dc67b0ce66c5bed876e8060cb18702bb80c

test:
  secret_key_base: 9ce34a8ea6e0fbed8f625a6038abec5531ed1f75d8ef73648562fed3715fe681826a8986d463039e3e66bf8ec7ddd1fa53a5a2f16c7a25caf029eebd93efe96b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
